### ISSUE TITLE
incompatibility with .netframework 4.6

### ISSUE THREAD

**Issue by abbyclaw100** [Devoxin/SharpLink#12]
when installing via nuget, i get this error: `Could not install package 'SharpLink 1.0.0-beta-0001'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`
is there a way around this? or do i need to change the target of my project?

**Comment by NovusTheory** [comment]
Currently .NETFramework has some issues with being targeted as it's not in our target frameworks. But there is also some bugs with using .NETFramework in terms of the WebSocket. We are working on implementing WebSocket4Net for those that use .NETFramework (#11).

Currently though .NETFramework 4.6.1 and above *does* support adding the package (or from source it may work) but the library may fail to connect to the Lavalink WebSocket the first time (works on retry) but it may fail indefinitely. This is due to a bug in Microsoft's WebSocket programming which is why we are working on implementing WebSocket4Net.

**Comment by abbyclaw100** [comment]
so i should just wait?

**Comment by NovusTheory** [comment]
Your best option is to wait if you don't want to target .NETCore or a different version of .NETFramework and risk having a minor connection bug (or major if you run into it failing to connect every time)

**Comment by abbyclaw100** [comment]
okay
