### ISSUE TITLE
Events improperly named

### ISSUE THREAD

**Issue by Giggitybyte** [Devoxin/SharpLink#8]
Super minor not-even-really-important issue: `PlayerEnd`, `PlayerException`, and `PlayerStuck` events in `LavalinkManager` should be named `TrackEnd`, `TrackException`, and `TrackStuck` as per the [Lavalink implementation](https://github.com/Frederikam/Lavalink/blob/master/IMPLEMENTATION.md).

**Comment by NovusTheory** [comment]
This was mostly a design choice to because the tracks are associated with a player and only one track can be played at a time so it's more so implied thus the track had an exception. The original events were Player.Exception and etc. I'd think that the class name being LavalinkManager plus having TrackException gives a misleading impression that it wa a track on the manager class rather than implying that the player had an issue with the track

**Comment by Devoxin** [comment]
Consistency would be nice though, And generally it's not the player that throws the exception, it's the track. Additionally a player doesn't necessarily end, The currently playing song does though

**Comment by Giggitybyte** [comment]
^ pretty much what I was getting at.

**Comment by NovusTheory** [comment]
Okay, you make a good point. Any feedback on whether you'd like PlayerTrackException etc.. or just TrackException?
